# config/policy_rules.py
# Extracted from KMP-OHS-POL-001 — Occupational Health & Safety Compliance Policy Manual
# This file is auto-generated by src/detection/policy_parser.py
# Do NOT edit manually — re-run the parser if the source PDF changes.

COMPLIANCE_RULES = {
    "walkway_violation": {
        "class_id": 0,
        "behavior_class": "Safe Walkway Violation",
        "safe_behavior": "Safe Walkway",
        "domain": "Pedestrian Movement",
        "policy_section": "Section 3.3.2",
        "observable_indicator": "Person positioned outside green-painted floor boundary markings",
        "hazard_context": "Exposure to forklift and machinery collision risk in non-pedestrian zones",
        "severity": "CRITICAL",
        "severity_rationale": (
            "Explicitly designated highest-frequency unsafe behavior at this facility "
            "(Section 3.3.2 WARNING callout). Highest recurrence rate documented."
        ),
        "alert_callout": "WARNING",
    },
    "unauthorized_intervention": {
        "class_id": 1,
        "behavior_class": "Unauthorized Intervention",
        "safe_behavior": "Authorized Intervention",
        "domain": "Equipment Interaction",
        "policy_section": "Section 4.3.2",
        "observable_indicator": (
            "Person interacting with production equipment while wearing red-black vest "
            "or no green authorization vest, or missing required safety equipment"
        ),
        "hazard_context": "Injury to intervening individual and disruption of production; equipment misuse",
        "severity": "HIGH",
        "severity_rationale": (
            "CRITICAL SAFETY NOTICE in policy (Section 4.3.2). Active personnel-equipment "
            "contact without authorization. Direct injury risk present."
        ),
        "alert_callout": "CRITICAL SAFETY NOTICE",
    },
    "opened_panel_cover": {
        "class_id": 2,
        "behavior_class": "Opened Panel Cover",
        "safe_behavior": "Closed Panel Cover",
        "domain": "Electrical Safety",
        "policy_section": "Section 5.2.2",
        "observable_indicator": "Electrical panel cover observed in open position during production operations",
        "hazard_context": "Personnel exposure to live electrical components of connected machinery",
        "severity": "MEDIUM",
        "severity_rationale": (
            "State-based condition (WARNING callout, Section 5.2.2). No concurrent personnel "
            "exposure confirmed at detection time; hazard present but not yet acute."
        ),
        "alert_callout": "WARNING",
    },
    "forklift_overload": {
        "class_id": 3,
        "behavior_class": "Carrying Overload with Forklift",
        "safe_behavior": "Safe Carrying",
        "domain": "Forklift Load Management",
        "policy_section": "Section 6.3.2",
        "observable_indicator": "Forklift observed carrying 3 or more standardized blocks in a single load",
        "hazard_context": "Vehicle instability and tip-over risk during travel, maneuvering, and loading",
        "severity": "HIGH",
        "severity_rationale": (
            "CRITICAL SAFETY NOTICE in policy (Section 6.3.2). Active operational hazard "
            "with vehicle instability risk; personnel may be in vicinity."
        ),
        "alert_callout": "CRITICAL SAFETY NOTICE",
    },
}

# Severity tier → escalation routing (Module 3)
ESCALATION_ROUTING = {
    "LOW":      {"db_log": True,  "realtime_alert": False, "action_label": "Logged to DB"},
    "MEDIUM":   {"db_log": True,  "realtime_alert": False, "action_label": "Logged to DB"},
    "HIGH":     {"db_log": True,  "realtime_alert": True,  "action_label": "Real-time alert triggered + DB log"},
    "CRITICAL": {"db_log": True,  "realtime_alert": True,  "action_label": "Real-time alert triggered + DB log"},
}

# Severity tier color coding for dashboard
SEVERITY_COLORS = {
    "LOW":      "#22c55e",   # green
    "MEDIUM":   "#f59e0b",   # amber
    "HIGH":     "#ef4444",   # red
    "CRITICAL": "#7c3aed",   # purple
}

# Class ID → rule key mapping (matches dataset label indices)
CLASS_ID_TO_RULE = {
    0: "walkway_violation",
    1: "unauthorized_intervention",
    2: "opened_panel_cover",
    3: "forklift_overload",
}
